server:
  port: 8007

spring:
  application:
    name: CLOUD-PAYMENT-SERVEICE

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}