server:
  port: 3344

spring:
  application:
    name: cloud-config-cenrer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MissPholipop/spring-cloud-config.git
          search-paths: spring-cloud-config
          username: yourusername
          password: 'yourpassword'
      label: master
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
